name: RSS Weather to GCP

on:
  schedule: 
    - cron: '*/1 * * * *'  # Every 1 minute
  workflow_dispatch:

jobs:
  rss-pipeline:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests toml xmltodict google-cloud-pubsub google-cloud-storage

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Run RSS Script
        run: python scripts/rss_worker.py
